server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://172.16.1.99:3306/myblog?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Root123!
  rabbitmq:
    host: 172.16.1.99
    port: 5672
    username: test
    password: test
    publisher-confirm-type: CORRELATED
    publisher-returns: true #支持消息发送失败返回队列
  #thymelea模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #关闭缓存
    mode: HTML5 #设置模板类型
    encoding: utf-8  #设置编码
logging:
  config: classpath:log4j2.xml